name: Build AI City APK

# Trigger on push to main branch or manually
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      npc_count:
        description: 'Number of NPCs'
        required: false
        default: '10'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          git zip unzip \
          autoconf libtool pkg-config \
          zlib1g-dev libncurses-dev libncursesw5-dev \
          cmake libffi-dev libssl-dev \
          build-essential ccache

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Buildozer
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython==0.29.36

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Sign APK (optional)
      if: github.event_name == 'push'
      run: |
        # Optional: Add APK signing here if you have keystore
        echo "APK built successfully"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ai-city-experiment-apk
        path: bin/*.apk

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
